version: '3.8'

services:
  ros_publisher:
    build:
      context: ${PROJECT_DIR-.}
      dockerfile: Dockerfile
      args:
        - PROJECT_UID=${PROJECT_UID}
        - PROJECT_GID=${PROJECT_GID}
        - PROJECT_USER=${PROJECT_USER}
        - PROJECT_NAME=${PROJECT_NAME}
    container_name: ${PROJECT_NAME}_ros_publisher
    networks:
      - ros_net
    environment:
      - ROS_MASTER_URI=http://172.18.0.2:11311
      - ROS_IP=172.18.0.2
    user: "${PROJECT_UID}:${PROJECT_GID}"
    volumes:
      - ${PROJECT_DIR-.}/src/nimbro_network:/home/${PROJECT_USER}/${PROJECT_NAME}/src/nimbro_network
    command: bash

  ros_subscriber:
    build:
      context: ${PROJECT_DIR-.}
      dockerfile: Dockerfile
      args:
        - PROJECT_UID=${PROJECT_UID}
        - PROJECT_GID=${PROJECT_GID}
        - PROJECT_USER=${PROJECT_USER}
        - PROJECT_NAME=${PROJECT_NAME}
    container_name: ${PROJECT_NAME}_ros_subscriber
    networks:
      - ros_net
    environment:
      - ROS_MASTER_URI=http://172.18.0.2:11311
      - ROS_IP=172.18.0.3
    user: "${PROJECT_UID}:${PROJECT_GID}"
    volumes:
      - ${PROJECT_DIR-.}/src/nimbro_network:/home/${PROJECT_USER}/${PROJECT_NAME}/src/nimbro_network
    command: bash

  ros_build:
    build:
      context: ${PROJECT_DIR-.}
      dockerfile: Dockerfile
      args:
        - PROJECT_UID=${PROJECT_UID}
        - PROJECT_GID=${PROJECT_GID}
        - PROJECT_USER=${PROJECT_USER}
        - PROJECT_NAME=${PROJECT_NAME}
    container_name: ${PROJECT_NAME}_ros_build
    networks:
      - ros_net
    environment:
      - ROS_MASTER_URI=http://172.18.0.4:11311
      - ROS_IP=172.18.0.4
    user: "${PROJECT_UID}:${PROJECT_GID}"
    volumes:
      - ${PROJECT_DIR-.}/src/nimbro_network:/home/${PROJECT_USER}/${PROJECT_NAME}/src/nimbro_network
    command: bash
    tty: true
    stdin_open: true
    restart: no

networks:
  ros_net:
    driver: bridge
    ipam:
      config:
        - subnet: 172.18.0.0/16
