
# Common configuration for all services
# Define networks first
networks:
  ros_net:
    driver: bridge
x-common: &common
  build:
    context: .
    args:
      PROJECT_NAME: ${PROJECT_NAME}
      PROJECT_USER: ${PROJECT_USER}
      PROJECT_UID: ${PROJECT_UID}
      PROJECT_GID: ${PROJECT_GID}
  user: "${PROJECT_UID}:${PROJECT_GID}"
  volumes:
    - .:/home/${PROJECT_USER}/${PROJECT_NAME}
  networks:
    - ros_net

services:
  ros_publisher:
    <<: *common
    container_name: ${PROJECT_NAME}-ros_publisher
    tty: true  # Keep the container open for interaction
    stdin_open: true

  ros_subscriber:
    <<: *common
    container_name: ${PROJECT_NAME}-ros_subscriber
    tty: true  # Keep the container open for interaction
    stdin_open: true

  ros_dev:
    <<: *common
    container_name: ${PROJECT_NAME}-ros_dev
    command: /bin/bash  # Start with an interactive shell for development
    tty: true  # Keep the container open for interaction
    stdin_open: true

